### PR TITLE
Support multiple endpoints for ceph cosi driver

### PR DESCRIPTION
**Pull request by thotz**
Currently Ceph COSI driver is deployed for a rgw endpoints but it need to support multiple endpoints generically. The information related to where to create bucket and all can be passed via BucketClass and BucketAccesClass. So Ceph COSI Driver nolonger needs object store while starting up.

### CODE REVIEW

**Comment by thotz** [comment]
FYI @giubacc

**Comment by giubacc** [comment]
@thotz thanks for pointing this out.
A question for when I will have some time to devote to this: is this an enhancement in the COSI specification?

```
parameters:
  ObjectStoreUserSecretName: <secret name>
  ObjectStoreNamespace: <namespace>
```

Or something introduced specifically for Ceph?

**Comment by thotz** [comment]
> @thotz thanks for pointing this out. A question for when I will have some time to devote to this: is this an enhancement in the COSI specification?
> 
> ```
> parameters:
>   ObjectStoreUserSecretName: <secret name>
>   ObjectStoreNamespace: <namespace>
> ```
> 
> Or something introduced specifically for Ceph?

The parameter string map is already part of BucketClass and BucketAccessClass Spec. This struct is opaque to the COSI controller and will be passed directly to the driver.  The value-pairs are just specific to ceph only, the driver can choose any values. Currently, the struct is not passed properly for `DriverDeleteBucket()` and `DriverRevokeAccess()` APIs. The first one is already addressed by https://github.com/kubernetes-sigs/container-object-storage-interface-spec/pull/42 and second one by https://github.com/kubernetes-sigs/container-object-storage-interface-spec/pull/44

**Comment by BlaineEXE** [comment]
Naming this `ObjectStoreNamespace` takes a Rook-centric view of the config rather than a Kubernetes-centric view. I would suggest one of two things:
- Make `ObjectStoreUserSecret` take a namespaced name or
- Use `ObjectStoreUserSecretName` and `ObjectStoreUserSecretNamespace`

**Pull request merged**
