### PR TITLE
feat: structed log

### PR DESCRIPTION
**Pull request by jonyhy96**
ErrorS is not like Errorf 
it will print error log like this 
```bash
E1112 10:13:32.364480       1 provisioner.go:68] "failed to create bucket %q" err="failed to create bucket \"test-3a089556-038d-4950-b304-ff53326b6e5a\" error RequestError: send request failed\ncaused by: Put \"http://rgw:8080/test-3a089556-038d-4950-b304-ff53326b6e5a\": dial tcp: lookup rgw on 10.96.0.10:53: no such host" test-3a089556-038d-4950-b304-ff53326b6e5a="(MISSING)"
```

### CODE REVIEW

**Review by thotz — COMMENTED** [review]
@jonyhy96 : I can understand that `%q` need to removed but why `"bucketName"` is added?

**Comment by jonyhy96** [comment]
This is because structed log needs to be `keyval` pair

**Comment by thotz** [comment]
> This is because structed log needs to be `keyval` pair

Thanks for explaining, do you like to pick up #2 ?

**Comment by jonyhy96** [comment]
> > This is because structed log needs to be `keyval` pair
> 
> Thanks for explaining, do you like to pick up #2 ?

Sure

**Comment by jonyhy96** [comment]
done @thotz

**Review by thotz — APPROVED** [review]

**Comment by thotz** [comment]
> done @thotz

Thanks for taking it up

**Pull request merged**
